---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-ha-cluster
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KindCluster
    name: test-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KindCluster
    name: test-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KindCluster
metadata:
  name: test-ha-cluster
spec:
  kindConfigRef:
    name: test-ha-cluster-config
    key: config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-ha-cluster-config
data:
  config: |
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
    - role: control-plane
    - role: control-plane
    - role: worker
