---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-cluster
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KindCluster
    name: test-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KindCluster
    name: test-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KindCluster
metadata:
  name: test-cluster
